services:
  webserver:
    # image: webserver
    build:
      context: ./webserver
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./webserver
          action: sync
          target: /app
    ports:
      - 5002:5002
  client:
    # image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./client
          action: sync
          target: /app
    ports:
      - 5173:5173
